---
- name: "PRELIM | Run apt update"
  apt:
      update_cache: yes
  when:
      - ubtu20cis_rule_1_4_1

- name: "PRELIM | Check for autofs service"
  shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: ubtu20cis_autofs_service_status
  changed_when: false
  check_mode: false
  when:
      - ubtu20cis_rule_1_1_23
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for avahi-daemon service"
  shell: "systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"
  register: avahi_service_status
  changed_when: false
  check_mode: false
  when:
      - ubtu20cis_rule_2_2_3
  tags:
      - skip_ansible_lint