---
- name: "2.1.1 | PATCH | Ensure xinetd is not installed"
  apt:
      name: xinetd
      state: absent
  when:
      - ubtu20cis_rule_2_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.1
      - xinetd

- name: "2.1.2 | PATCH | Ensure openbsd-inetd is not installed"
  apt:
      name: openbsd-inetd
      state: absent
  when:
      - ubtu20cis_rule_2_1_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.2
      - openbsd-inetd

- name: "2.2.1.1 | PATCH | Ensure time synchronization is in use"
  apt:
      name: "{{ ubtu20cis_time_sync_tool }}"
      state: present
  when:
      - ubtu20cis_rule_2_2_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.1.1
      - chrony

- name: "2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured"
  block:
      - name: "2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured | Remove ntp and chrony"
        apt:
            name: ['ntp', 'chrony']
            state: absent

      - name: "2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured | Set configuration for systemd-timesyncd"
        lineinfile:
            path: /etc/systemd/timesyncd.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: "{{ item.insertafter }}"
        with_items:
            - { regexp: '^\[Time\]', line: '[Time]', insertafter: EOF }
            - { regexp: '^#NTP|^NTP', line: 'NTP={{ ubtu20cis_ntp_server_list }}', insertafter: '\[Time\]' }
            - { regexp: '^#FallbackNTP|^FallbackNTP', line: 'FallbackNTP={{ ubtu20cis_ntp_fallback_server_list }}', insertafter: '\[Time\]' }
            - { regexp: '^#RootDistanceMaxSec|^RootDistanceMaxSec', line: 'RootDistanceMaxSec=1', insertafter: '\[Time\]'}

      - name: "2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured | Start and enable the systemd-timesyncd service"
        systemd:
            name: systemd-timesyncd.service
            state: started
            enabled: yes
            masked: no

      - name: "2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured | Set timedatectl to ntp"
        command: timedatectl set-ntp true
  when:
      - ubtu20cis_rule_2_2_1_2
      - ubtu20cis_time_sync_tool == "systemd-timesyncd"
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - rule_2.2.1.2
      - systemd-timesyncd

- name: "2.2.1.3 | PATCH | Ensure chrony is configured"
  block:
      - name: "2.2.1.3 | PATCH | Ensure chrony is configured | Remove ntp"
        apt:
            name: ntp
            state: absent

      - name: "2.2.1.3 | PATCH | Ensure chrony is configured | Disable/Mask systemd-timesyncd"
        systemd:
            name: systemd-timesyncd
            state: stopped
            enabled: no
            masked: yes

      - name: "2.2.1.3 | AUDIT | Ensure chrony is configured | Check for chrony user"
        shell: grep {{ ubtu20cis_chrony_user }} /etc/passwd
        changed_when: false
        failed_when: false
        register: ubtu20cis_2_2_1_3_chrony_user_status

      - name: "2.2.1.3 | PATCH | Ensure chrony is configured | Set chrony.conf file"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.2.1.3 | PATCH | Ensure chrony is configured | Create chrony user"
        user:
            name: "{{ ubtu20cis_chrony_user }}"
            shell: /usr/sbin/nologin
            system: true
        when: ubtu20cis_2_2_1_3_chrony_user_status.stdout != ""

      - name: "2.2.1.3 | PATCH | Ensure chrony is configured | Set option to use chrony user"
        lineinfile:
            path: /etc/default/chrony
            regexp: '^DAEMON_OPTS'
            line: 'DAEMON_OPTS="-u _chrony"'
  when:
      - ubtu20cis_rule_2_2_1_3
      - ubtu20cis_time_sync_tool == "chrony"
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.1.3
      - chrony

- name: "2.2.1.4 | PATCH | Ensure ntp is configured"
  block:
      - name: "2.2.1.4 | PATCH | Ensure ntp is configured | Remove chrony"
        apt:
            name: chrony
            state: absent

      - name: "2.2.1.4 | PATCH | Ensure ntp is configured | Disable/Mask systemd-timesyncd"
        systemd:
            name: systemd-timesyncd
            state: stopped
            enabled: no
            masked: yes

      - name: "2.2.1.4 | PATCH | Ensure ntp is configured | Set ntp.conf settings"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.2.1.4 | PATCH | Ensure ntp is configured | Modify sysconfig/ntpd"
        lineinfile:
            path: /etc/sysconfig/ntpd
            regexp: "{{ item.regexp }}"
            line: "{{ item. line }}"
            create: yes
        with_items:
            - { regexp: '^OPTIONS', line: 'OPTIONS="-u ntp:ntp"'}
            - { regexp: '^NTPD_OPTIONS', line: 'NTPD_OPTIONS="-u ntp:ntp"' }

      - name: "2.2.1.4 | PATCH | Ensure ntp is configured | Modify /etc/init.d/npt"
        lineinfile:
            path: /etc/init.d/ntp
            regexp: '^RUNAUSER'
            line: 'RUNAUSER=npt'
  when:
      - ubtu20cis_rule_2_2_1_4
      - ubtu20cis_time_sync_tool == "ntp"
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.1.4
      - ntp

- name: "2.2.2 | PATCH | Ensure X Window System is not installed"
  apt:
      name: xserver-xorg*
      state: absent
  when:
      - ubtu20cis_rule_2_2_2
      - not ubtu20cis_xwindows_required
  tags:
      - level1-server

      - patch
      - rule_2.2.2
      - xwindows

- name: "2.2.3 | PATCH | Ensure Avahi Server is not installed"
  block:
      - name: "2.2.3 | PATCH | Ensure Avahi Server is not installed | Stop/Disable avahi-daemon.service"
        service:
            name: avahi-daemon.service
            state: stopped
            enabled: no
        when: avahi_service_status.stdout == "loaded"

      - name: "2.2.3 | PATCH | Ensure Avahi Server is not installed | Stop/Disable avahi-daemon.socket"
        service:
            name: avahi-daemon.socket
            state: stopped
            enabled: no
        when: avahi_service_status.stdout == "loaded"

      - name: "2.2.3 | PATCH | Ensure Avahi Server is not installed | Remove avahi-daemon"
        apt:
            name: avahi-daemon
            state: absent
  when:
      - ubtu20cis_rule_2_2_3
      - not ubtu20cis_avahi_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.3
      - avahi
      - services

- name: "2.2.4 | PATCH | Ensure CUPS is not installed"
  apt:
      name: cups
      state: absent
  when:
      - ubtu20cis_rule_2_2_4
      - not ubtu20cis_cups_server
  tags:
      - level1-server
      - level2-workstation
      - patch
      - rule_2.2.4
      - cups
      - services

- name: "2.2.5 | PATCH | Ensure DHCP Server is not installed"
  apt:
      name: isc-dhcp-server
      state: absent
  when:
      - ubtu20cis_rule_2_2_5
      - not ubtu20cis_dhcp_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.5
      - dhcp
      - services

- name: "2.2.6 | PATCH | Ensure LDAP server is not installed"
  apt:
      name: slapd
      state: absent
  when:
      - ubtu20cis_rule_2_2_6
      - not ubtu20cis_ldap_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.6
      - ldap
      - services

- name: "2.2.7 | PATCH | Ensure NFS is not installed"
  apt:
      name: rpcbind
      state: absent
  when:
      - ubtu20cis_rule_2_2_7
      - not ubtu20cis_nfs_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.7
      - nfs
      - rpc
      - services

- name: "2.2.8 | PATCH | Ensure DNS Server is not installed"
  apt:
      name: bind9
      state: absent
  when:
      - ubtu20cis_rule_2_2_8
      - not ubtu20cis_dns_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.8
      - dns
      - service

- name: "2.2.9 | PATCH | Ensure FTP Server is not installed"
  apt:
      name: vsftpd
      state: absent
  when:
      - ubtu20cis_rule_2_2_9
      - not ubtu20cis_vsftpd_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.9
      - ftp
      - service

- name: "2.2.10 | PATCH | Ensure HTTP server is not installed"
  apt:
       name: apache2
       state: absent
  when:
      - ubtu20cis_rule_2_2_10
      - not ubtu20cis_httpd_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.10
      - httpd
      - service

- name: "2.2.11 | PATCH | Ensure IMAP and POP3 server are not installed"
  apt:
      name: ['dovecot-imapd', 'dovecot-pop3d']
      state: absent
  when:
      - ubtu20cis_rule_2_2_11
      - not ubtu20cis_dovecot_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.11
      - dovecot
      - service

- name: "2.2.12 | PATCH | Ensure Samba is not installed"
  apt:
      name: samba
      state: absent
  when:
      - ubtu20cis_rule_2_2_12
      - not ubtu20cis_smb_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.12
      - samba
      - service