---
- name: "4.1.1.1 | PATCH | Ensure auditd is installed"
  apt:
      name: ['auditd', 'audispd-plugins']
      state: present
  when:
      - ubtu20cis_rule_4_1_1_1
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.1.1
      - auditd

- name: "4.1.1.2 | PATCH | Ensure auditd service is enabled"
  service:
      name: auditd
      state: started
      enabled: yes
  when:
      - ubtu20cis_rule_4_1_1_2
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.1.2
      - auditd

- name: "4.1.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
      replace: '\1"\2 audit=1"'
      follow: yes
  ignore_errors: yes
  notify: grub update
  when:
      - ubtu20cis_rule_4_1_1_3
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4_1_1_3
      - auditd

- name: "4.1.1.4 | PATCH | Ensure audit_backlog_limit is sufficient"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit_backlog_limit={{ ubtu20cis_audit_back_log_limit }})(?:")'
      replace: '\1"\2 audit_backlog_limit={{ ubtu20cis_audit_back_log_limit }}"'
      follow: yes
  ignore_errors: yes
  notify: grub update
  when:
      - ubtu20cis_rule_4_1_1_4
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.1.4
      - auditd

- name: "4.1.2.1 | PATCH | Ensure audit log storage size is configured"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file( |=)"
      line: "max_log_file = {{ ubtu20cis_max_log_file_size }}"
      state: present
  notify: restart auditd
  when:
      - ubtu20cis_rule_4_1_2_1
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.2.1
      - auditd

- name: "4.1.2.2 | PATCH | Ensure audit logs are not automatically deleted"
  lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^max_log_file_action'
      line: "max_log_file_action = {{ ubtu20cis_auditd['max_log_file_action'] }}"
  notify: restart auditd
  when:
      - ubtu20cis_rule_4_1_2_2
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.2.2
      - auditd

- name: "4.1.2.3 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items:
      - { regexp: '^space_left_action', line: 'space_left_action = email' }
      - { regexp: '^action_mail_acct', line: 'action_mail_acct = root' }
      - { regexp: '^admin_space_left_action = halt', line: 'admin_space_left_action = halt' }
  notify: restart auditd
  when:
      - ubtu20cis_rule_4_1_2_3
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.2.3
      - auditd

