---
- name: "4.1.1.1 | PATCH | Ensure auditd is installed"
  apt:
      name: ['auditd', 'audispd-plugins']
      state: present
  when:
      - ubtu20cis_rule_4_1_1_1
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.1.1
      - auditd

- name: "4.1.1.2 | PATCH | Ensure auditd service is enabled"
  service:
      name: auditd
      state: started
      enabled: yes
  when:
      - ubtu20cis_rule_4_1_1_2
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.1.2
      - auditd

- name: "4.1.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
      replace: '\1"\2 audit=1"'
      follow: yes
  ignore_errors: yes
  notify: grub update
  when:
      - ubtu20cis_rule_4_1_1_3
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4_1_1_3
      - auditd

- name: "4.1.1.4 | PATCH | Ensure audit_backlog_limit is sufficient"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit_backlog_limit={{ ubtu20cis_audit_back_log_limit }})(?:")'
      replace: '\1"\2 audit_backlog_limit={{ ubtu20cis_audit_back_log_limit }}"'
      follow: yes
  ignore_errors: yes
  notify: grub update
  when:
      - ubtu20cis_rule_4_1_1_4
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_4.1.1.4
      - auditd
