---
- name: "3.1.1 | PATCH | Disable IPv6"
  block:
      - name: "3.1.1 | AUDIT | Disable IPv6 | Get currnet GRUB_CMDLINE_LINUX settings"
        shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        register: ubtu20cis_3_1_1_grub_cmdline_linux_settings

      - name: "3.1.1 | PATCH | Disable IPv6 | Add ipv6.disable if does not exist"
        lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX'
            line: 'GRUB_CMDLINE_LINUX="{{ ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout }} ipv6.disable=1"'
        when: "'ipv6.disable' not in ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout"
        notify: grub update

      - name: "3.1.1 | PATCH | Disable IPv6 | Set ipv6.disable to 1 if exists"
        replace:
            path: /etc/default/grub
            regexp: 'ipv6\.disable=.'
            replace: 'ipv6.disable=1'
        when: "'ipv6.disable' in ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout"
        notify: grub update
  when:
      - ubtu20cis_rule_3_1_1
      - not ubtu20cis_ipv6_required
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_3.1.1
      - ipv6

- name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Check for network-manager tool"
        shell: dpkg -l | grep network-manager
        changed_when: false
        failed_when: false
        register: ubtu20cis_3_1_2_network_manager_status

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Disable wireless if network-manager installed"
        command: nmcli radio all off
        changed_when: ubtu20cis_3_1_2_nmcli_radio_off.rc == 0
        register: ubtu20cis_3_1_2_nmcli_radio_off
        when: ubtu20cis_3_1_2_network_manager_status.stdout != ""

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Warn about wireless if network-manager not installed"
        debug:
            msg: "ALERT!!!! You need to disable wireless interfaces manually since network-manager is not installed"
        when: ubtu20cis_3_1_2_network_manager_status.stdout == ""
  when:
      - ubtu20cis_rule_3_1_2
  tags:
      - level1-server
      - level2-workstation
      - patch
      - rule_3.1.2
      - wireless