---
- name: "3.1.1 | PATCH | Disable IPv6"
  block:
      - name: "3.1.1 | AUDIT | Disable IPv6 | Get currnet GRUB_CMDLINE_LINUX settings"
        shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        register: ubtu20cis_3_1_1_grub_cmdline_linux_settings

      - name: "3.1.1 | PATCH | Disable IPv6 | Add ipv6.disable if does not exist"
        lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX'
            line: 'GRUB_CMDLINE_LINUX="{{ ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout }} ipv6.disable=1"'
        when: "'ipv6.disable' not in ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout"
        notify: grub update

      - name: "3.1.1 | PATCH | Disable IPv6 | Set ipv6.disable to 1 if exists"
        replace:
            path: /etc/default/grub
            regexp: 'ipv6\.disable=.'
            replace: 'ipv6.disable=1'
        when: "'ipv6.disable' in ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout"
        notify: grub update

      - name: "3.1.1 | PATCH | Disable IPv6 | Remove net.ipv6.conf.all.disable_ipv6"
        lineinfile:
            path: /etc/sysctl.conf
            regexp: '^net.ipv6.conf.all.disable_ipv6.*'
            state: absent
  when:
      - ubtu20cis_rule_3_1_1
      - not ubtu20cis_ipv6_required
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_3.1.1
      - ipv6

- name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Check for network-manager tool"
        shell: dpkg -l | grep network-manager
        changed_when: false
        failed_when: false
        register: ubtu20cis_3_1_2_network_manager_status

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Disable wireless if network-manager installed"
        command: nmcli radio all off
        changed_when: ubtu20cis_3_1_2_nmcli_radio_off.rc == 0
        register: ubtu20cis_3_1_2_nmcli_radio_off
        when: ubtu20cis_3_1_2_network_manager_status.stdout != ""

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Warn about wireless if network-manager not installed"
        debug:
            msg: "ALERT!!!! You need to disable wireless interfaces manually since network-manager is not installed"
        when: ubtu20cis_3_1_2_network_manager_status.stdout == ""
  when:
      - ubtu20cis_rule_3_1_2
  tags:
      - level1-server
      - level2-workstation
      - patch
      - rule_3.1.2
      - wireless

- name: "3.2.1 | PATCH | Ensure packet redirect sending is disabled"
  sysctl:
      name: "{{ item }}"
      value: '0'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - net.ipv4.conf.all.send_redirects
      - net.ipv4.conf.default.send_redirects
  notify: sysctl flush ipv4 route table
  when:
      - ubtu20cis_rule_3_2_1
      - not ubtu20cis_is_router
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.2.1
      - packet_redirect
      - sysctl

- name: "3.2.2 | PATCH | Ensure IP forwarding is disabled"
  block:
      - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | IPv4 settings"
        sysctl:
            name: net.ipv4.ip_forward
            value: '0'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        notify:
            - sysctl flush ipv4 route table

      - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | IPv6 settings"
        sysctl:
            name: net.ipv6.conf.all.forwarding
            value: '0'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        notify:
            - sysctl flush ipv6 route table
        when: ubtu20cis_ipv6_required
  when:
      - ubtu20cis_rule_3_2_2
      - not ubtu20cis_is_router
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.2.2
      - ip_forwarding
      - sysctl

- name: "3.3.1 | PATCH | Ensure source routed packets are not accepted"
  block:
      - name: "3.3.1 | PATCH | Ensure source routed packets are not accepted | IPv4 settings"
        sysctl:
            name: "{{ item }}"
            value: '0'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        with_items:
            - net.ipv4.conf.all.accept_source_route
            - net.ipv4.conf.default.accept_source_route
        notify: sysctl flush ipv4 route table

      - name: "3.3.1 | PATCH | Ensure source routed packets are not accepted | IPv6 settings"
        sysctl:
            name: "{{ item }}"
            value: '0'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        with_items:
            - net.ipv6.conf.all.accept_source_route
            - net.ipv6.conf.default.accept_source_route
        notify: sysctl flush ipv6 route table
        when: ubtu20cis_ipv6_required
  when:
      - ubtu20cis_rule_3_3_1
      - not ubtu20cis_is_router
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.1
      - routed_packets
      - sysctl

- name: "3.3.2 | PATCH | Ensure ICMP redirects are not accepted"
  block:
      - name: "3.3.2 | PATCH | Ensure ICMP redirects are not accepted | IPv4 settings"
        sysctl:
            name: "{{ item }}"
            value: '0'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        with_items:
            - net.ipv4.conf.all.accept_redirects
            - net.ipv4.conf.default.accept_redirects
        notify: sysctl flush ipv4 route table

      - name: "3.3.2 | PATCH | Ensure ICMP redirects are not accepted | IPv6 settings"
        sysctl:
            name: "{{ item }}"
            value: '0'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        with_items:
            - net.ipv6.conf.all.accept_redirects
            - net.ipv6.conf.default.accept_redirects
        notify: sysctl flush ipv6 route table
        when: ubtu20cis_ipv6_required
  when:
      - ubtu20cis_rule_3_3_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.2
      - icmp
      - sysctl

- name: "3.3.3 | PATCH | Ensure secure ICMP redirects are not accepted"
  sysctl:
      name: "{{ item }}"
      value: '0'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - net.ipv4.conf.all.secure_redirects
      - net.ipv4.conf.default.secure_redirects
  notify: sysctl flush ipv4 route table
  when:
      - ubtu20cis_rule_3_3_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.3
      - icmp
      - sysctl

- name: "3.3.4 | PATCH | Ensure suspicious packets are logged"
  sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - net.ipv4.conf.all.log_martians
      - net.ipv4.conf.default.log_martians
  notify: sysctl flush ipv4 route table
  when:
      - ubtu20cis_rule_3_3_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.4
      - suspicious_packets
      - sysctl

- name: "3.3.5 | PATCH | Ensure broadcast ICMP requests are ignored"
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  notify: sysctl flush ipv4 route table
  when:
      - ubtu20cis_rule_3_3_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.5
      - icmp
      - sysctl

- name: "3.3.6 | PATCH | Ensure bogus ICMP responses are ignored"
  sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  notify: sysctl flush ipv4 route table
  when:
      - ubtu20cis_rule_3_3_6
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.6
      - icmp
      - sysctl

- name: "3.3.7 | PATCH | Ensure Reverse Path Filtering is enabled"
  sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - net.ipv4.conf.all.rp_filter
      - net.ipv4.conf.default.rp_filter
  notify: sysctl flush ipv4 route table
  when:
      - ubtu20cis_rule_3_3_7
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.7
      - reverse_path_filtering
      - sysctl

- name: "3.3.8 | PATCH | Ensure TCP SYN Cookies is enabled"
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  notify: sysctl flush ipv4 route table
  when:
      - ubtu20cis_rule_3_3_8
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.8
      - tcp_syn_cookies
      - sysctl

- name: "3.3.9 | PATCH | Ensure IPv6 router advertisements are not accepted"
  sysctl:
      name: "{{ item }}"
      value: '0'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - net.ipv6.conf.all.accept_ra
      - net.ipv6.conf.default.accept_ra
  notify: sysctl flush ipv6 route table
  when:
      - ubtu20cis_rule_3_3_9
      - ubtu20cis_ipv6_required
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.3.9
      - ipv6
      - router_advertisements
      - sysctl
