---
- name: grub update
  command: update-grub
  failed_when: false

- name: reload gdm3
  command: dpkg-reconfigure gdm3
  failed_when: false

- name: restart postfix
  service:
      name: postfix
      state: restarted

- name: restart exim4
  service:
      name: exim4
      state: restarted